name: First Action
on: [workflow_dispatch]
jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: Clone code
              uses: actions/checkout@v4
            - name: Run output
              run: echo "This is echo!"